### PR TITLE
Moved awaiting to a dev dependency and expanded allowed engines

### PR DESCRIPTION
**Pull request by STRd6**
I noticed `awaiting` was only used in the tests so I moved it to a dev dependency. I also noticed that this package works fine for me on node 6 so I expanded the viable engines.

Let me know if there's anything more you'd like me to do here, and thanks for the great module!

### CODE REVIEW

**Comment by sveisvei** [comment]
Would be awesome to get this in - running node 6 here!

**Comment by sveisvei** [comment]
ping @hunterloftis :)

**Comment by SimenB** [comment]
I've forked and published a version with this PR applied: https://www.npmjs.com/package/@finn-no/stoppable

**Comment by gergelyke** [comment]
Thanks for the contribution @STRd6 ! 🎉

**Comment by STRd6** [comment]
:confetti_ball:

**Pull request merged**
